### ISSUE TITLE
如何指定z-index

### ISSUE THREAD

**Issue by vinz08** [aralejs/calendar#73]
配合arale-dialog使用时，dialog始终在calendar之上，设置参数zIndex不能生效。

**Comment by afc163** [comment]
```css
.ui-calendar {
  z-index: 1001;
}
```

or

```js
new Calendar({
  ...
}).after('show', function() {
  this.element.css('z-index', 1001);
});
```
